version: "2"

run:
  timeout: 5m
  tests: true

linters:
  # Start with no linters and explicitly enable the ones we want
  default: none

  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

  # Exclude test files from typecheck issues since Ginkgo/Gomega use dot imports
  # which can cause type resolution problems in golangci-lint
  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - typecheck
      - path: 'internal/testing/'
        linters:
          - typecheck

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
