before:
  # https://goreleaser.com/customization/hooks/
  hooks:
    - go mod tidy

builds:
  # Manager
  - id: manager
    main: ./
    binary: manager
    env: [CGO_ENABLED=0]
    goos:
    - linux
    goarch:
    - amd64
    - arm64

  # CLI
  - id: cli
    main: ./ozctl
    binary: ozctl
    env: [CGO_ENABLED=0]
    goos:
    - darwin
    goarch:
    - amd64
    - arm64

universal_binaries:
  - id: cli
    name_template: ozctl
    replace: true

dockers:
  # Local image only used for `make docker-load`
  - image_templates: ["{{ .Env.IMG }}"]
    dockerfile: Dockerfile
    use: buildx

  # Potential Release - AMD64
  - image_templates: ["ghcr.io/diranged/{{ .ProjectName }}:{{ .Version }}-amd64"]
    dockerfile: Dockerfile
    goarch: amd64
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/diranged/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/diranged/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

  # Potential Release - ARM64
  - image_templates: ["ghcr.io/diranged/{{ .ProjectName }}:{{ .Version }}-arm64v8"]
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/diranged/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/diranged/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0

docker_manifests:
  - name_template: ghcr.io/diranged/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/diranged/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/diranged/{{ .ProjectName }}:{{ .Version }}-arm64v8

  - name_template: ghcr.io/diranged/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/diranged/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/diranged/{{ .ProjectName }}:{{ .Version }}-arm64v8

# https://goreleaser.com/customization/release/
release:
  github:
    disable: false
    prerelease: auto
