---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-crds-wizardofoz-co-v1alpha1-execaccessrequest
  failurePolicy: Fail
  name: mexecaccessrequest.kb.io
  rules:
  - apiGroups:
    - crds.wizardofoz.co
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - execaccessrequests
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-crds-wizardofoz-co-v1alpha1-podaccessrequest
  failurePolicy: Fail
  name: mpodaccessrequest.kb.io
  rules:
  - apiGroups:
    - crds.wizardofoz.co
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - podaccessrequests
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-crds-wizardofoz-co-v1alpha1-execaccessrequest
  failurePolicy: Fail
  name: vexecaccessrequest.kb.io
  rules:
  - apiGroups:
    - crds.wizardofoz.co
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - execaccessrequests
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-crds-wizardofoz-co-v1alpha1-podaccessrequest
  failurePolicy: Fail
  name: vpodaccessrequest.kb.io
  rules:
  - apiGroups:
    - crds.wizardofoz.co
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - podaccessrequests
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /watch-v1-pod
  failurePolicy: Fail
  name: vpod.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - CONNECT
    resources:
    - pods/exec
    - pods/attach
  sideEffects: None
