# permissions for end users to view execaccesstemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: execaccesstemplate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oz
    app.kubernetes.io/part-of: oz
    app.kubernetes.io/managed-by: kustomize
  name: execaccesstemplate-viewer-role
rules:
- apiGroups:
  - templates.wizardofoz.co
  resources:
  - execaccesstemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - templates.wizardofoz.co
  resources:
  - execaccesstemplates/status
  verbs:
  - get
