# permissions for end users to edit execaccesstemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: execaccesstemplate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oz
    app.kubernetes.io/part-of: oz
    app.kubernetes.io/managed-by: kustomize
  name: execaccesstemplate-editor-role
rules:
- apiGroups:
  - crds.wizardofoz.co
  resources:
  - execaccesstemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crds.wizardofoz.co
  resources:
  - execaccesstemplates/status
  verbs:
  - get
