apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "oz.fullname" . }}-manager-role
  labels:
  {{- include "oz.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - crds.wizardofoz.co
  resources:
  - execaccessrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - rollouts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crds.wizardofoz.co
  resources:
  - execaccessrequests/finalizers
  verbs:
  - update
- apiGroups:
  - crds.wizardofoz.co
  resources:
  - execaccessrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crds.wizardofoz.co
  resources:
  - execaccesstemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crds.wizardofoz.co
  resources:
  - execaccesstemplates/finalizers
  verbs:
  - update
- apiGroups:
  - crds.wizardofoz.co
  resources:
  - execaccesstemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crds.wizardofoz.co
  resources:
  - execacesstemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crds.wizardofoz.co
  resources:
  - podaccessrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crds.wizardofoz.co
  resources:
  - podaccessrequests/finalizers
  verbs:
  - update
- apiGroups:
  - crds.wizardofoz.co
  resources:
  - podaccessrequests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crds.wizardofoz.co
  resources:
  - podaccesstemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crds.wizardofoz.co
  resources:
  - podaccesstemplates/finalizers
  verbs:
  - update
- apiGroups:
  - crds.wizardofoz.co
  resources:
  - podaccesstemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - bind
  - create
  - delete
  - escalate
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "oz.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oz
    app.kubernetes.io/instance: manager-rolebinding
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: oz
  {{- include "oz.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "oz.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "oz.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
