apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oz.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oz
    app.kubernetes.io/part-of: oz
  {{- include "oz.labels" . | nindent 4 }}
