apiVersion: v1
kind: Service
metadata:
  name: {{ include "oz.fullname" . }}-controller-manager-webhook-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
  {{- include "oz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    control-plane: controller-manager
    {{- include "oz.selectorLabels" . | nindent 4 }}
  ports:
    {{- .Values.webhookService.ports | toYaml | nindent 4 -}}
