apiVersion: templates.wizardoz.co/v1alpha1
kind: ExecAccessTemplate
metadata:
  labels:
    app.kubernetes.io/name: execaccesstemplate
    app.kubernetes.io/instance: execaccesstemplate-sample
    app.kubernetes.io/part-of: oz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: oz
  name: execaccesstemplate-sample
spec:
  # TODO(user): Add fields here
