apiVersion: crds.wizardofoz.co/v1alpha1
kind: PodAccessTemplate
metadata:
  name: deployment-example
spec:
  accessConfig:
    # todo: figure out why these are required
    maxDuration: 2h
    defaultDuration: 1h

    # A list of Kubernetes Groups that are allowed to request access through this template.
    allowedGroups:
      - admins
      - devs

    accessCommand: 'kubectl exec -ti -n {{ .Metadata.Namespace }} {{ .Metadata.Name }} -- /bin/bash'

  controllerTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example

  controllerTargetMutationConfig:
    command: [/bin/sleep, '999999']
    env:
      - name: FOO
        value: bar
    resources:
      requests:
        memory: 42Mi
        cpu: 100m
    securityContext:
      capabilities:
        add:
          - SYS_PTRACE

  maxMemory: 1Gi
  maxCpu: 1
  maxStorage: 1Gi
