package v1alpha1

import (
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RequestStatus provides a common set of .Status fields and functions. The goal is to
// conform to the interfaces.OzResource interface commonly across all of our core CRDs.
type RequestStatus struct {
	// Current status of the Access Template
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type" protobuf:"bytes,1,rep,name=conditions"`

	// Expiration indicates when this request expires.
	Expiration metav1.Time `json:"expiration,omitempty"`

	// Simple boolean to let us know if the resource is ready for use or not
	Ready bool `json:"ready,omitempty"`

	// AccessMessage is used to describe to the user how they can make use of their temporary access
	// request. Eg, for a PodAccessTemplate the value set here would be something like:
	//
	//   "Access Graned, connect to your pod with: kubectl exec -ti -n namespace pod-xyz -- /bin/bash"
	//
	AccessMessage string `json:"accessMessage,omitempty"`
}

func (in *RequestStatus) SetExpiration(t time.Time) {
	in.Expiration = metav1.Time{
		Time: t,
	}
}

func (in *RequestStatus) IsExpired() bool {
	return time.Now().After(in.Expiration.Time)
}

// DeepCopyInto is typically auto-generated by controller-gen. However, it seems that controller-gen
// fails when we include the ozResourceRequestStatus.Conditions field. Implementing our own DeepCopyInto function
// resolves this, but does put the responsibility on us to keep this updated.
func (in *RequestStatus) DeepCopyInto(out *RequestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}
