name: Build Artifacts

on:
  workflow_call: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Set up Go
        uses: ./.github/actions/setup-go

      - name: Build Artifacts
        run: make build

      - name: Check for diff
        run: git diff --exit-code

      - name: Upload Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: dist
          path: dist/**
