name: CI

on:
  push:
    tags-ignore: '*'

  pull_request: {}

jobs:
  detect-noop:
    runs-on: ubuntu-latest
    outputs:
      noop: ${{ steps.noop.outputs.should_skip }}
    steps:
      - name: Detect No-op Changes
        id: noop
        uses: fkirc/skip-duplicate-actions@v5.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths_ignore: '["**.md", "**.png", "**.jpg"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'
          concurrent_skipping: false

  build:
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'
    uses: ./.github/workflows/build.yaml

  docgen:
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'
    uses: ./.github/workflows/docgen.yaml

  lint:
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'
    uses: ./.github/workflows/lint.yaml

  unit-tests:
    needs: detect-noop
    if: needs.detect-noop.outputs.noop != 'true'
    uses: ./.github/workflows/test.yaml

  test-e2e:
    needs: build
    if: needs.detect-noop.outputs.noop != 'true'
    uses: ./.github/workflows/test-e2e.yaml

  publish-dry:
    needs: build
    if: needs.detect-noop.outputs.noop != 'true'
    uses: ./.github/workflows/publish.yaml
    with:
      publish: false
