name: Controller Release

on:
  push:
    tags:
      # https://semver.org/
      - '[0-9]+\.[0-9]+\.[0-9]+'
      - '[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+'

jobs:
  publish-docker:
    uses: ./.github/workflows/publish-docker.yaml
    with:
      push: true

  publish-cli:
    uses: ./.github/workflows/publish-cli.yaml
    with:
      release: true
