name: Controller Release

on:
  push:
    tags:
      # https://semver.org/
      - '[0-9]+\.[0-9]+\.[0-9]+'
      - '[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]+'

jobs:
  publish:
    uses: ./.github/workflows/publish.yaml
    with:
      push: true
      release: true
