name: Chart Test
on:
  workflow_call: {}
jobs:
  helm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for ct helm tool
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 3.10.2

      - uses: actions/setup-python@v5
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct --config ct.yaml list-changed)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> ${GITHUB_OUTPUT}
          fi

      - name: Run chart-testing (lint)
        run: ct --config ct.yaml lint

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.10.0

      - name: Install cert-manager
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.10.1/cert-manager.yaml
          kubectl wait deployment -l app.kubernetes.io/instance=cert-manager -n cert-manager --for=condition=Available=True

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct --config ct.yaml install
