name: Chart Test
on:
  workflow_call: {}
jobs:
  helm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 3.10.2

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct --config ct.yaml list-changed)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> ${GITHUB_OUTPUT}
          fi

      - name: Run chart-testing (lint)
        run: ct --config ct.yaml lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (inst}all)
        run: ct --config ct.yaml install
