name: Helm-Docs
on:
  workflow_call: {}
jobs:
  helm-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Run helm-docs
        run: make helm-docs
