name: CI

on:
  workflow_call: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: ./.github/actions/setup-go

      - name: Run Revive Action by pulling pre-built image
        uses: docker://morphy/revive-action:v2
        with:
          path: './...'
          config: revive.toml

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
