name: Lint
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: golint
        run: make lint
