name: CI

on:
  workflow_call: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # https://github.com/golangci/golangci-lint-action/issues/807
      #
      # when the files to be extracted are already present,
      # tar extraction in Golangci Lint fails with the "File exists"
      # errors. These files appear to be present because of
      # cache in setup-go, on disabling the cache we are no more seeing
      # such error. Cache is to be enabled once the fix is available for
      # this issue.
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version-file: "go.mod"

      - name: Run Revive Action by pulling pre-built image
        uses: docker://morphy/revive-action:v2
        with:
          path: './...'
          config: revive.toml

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m
