name: Release

on:
  push:
    branches: [main]
    tags-ignore: '*'

jobs:
  goreportcard:
    runs-on: ubuntu-latest
    steps:
      - uses: creekorful/goreportcard-action@v1.0

  build:
    uses: ./.github/workflows/build.yaml

  lint:
    uses: ./.github/workflows/lint.yaml

  unit-tests:
    uses: ./.github/workflows/test.yaml

  test-e2e:
    uses: ./.github/workflows/test-e2e.yaml

  publish:
    uses: ./.github/workflows/publish.yaml
    needs: [test-e2e, unit-tests, lint, build]
    with:
      push: true
