name: Release

on:
  push:
    branches: [main]
    tags-ignore: '*'

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  lint:
    uses: ./.github/workflows/lint.yaml

  unit-tests:
    uses: ./.github/workflows/test.yaml

  test-e2e:
    uses: ./.github/workflows/test-e2e.yaml

  publish-docker:
    uses: ./.github/workflows/publish-docker.yaml
    needs: [test-e2e, unit-tests, lint, build]
    with:
      push: true

  publish-cli:
    uses: ./.github/workflows/publish-cli.yaml
    needs: [test-e2e, unit-tests, lint, build]
    with:
      release: true
