name: Reusable Workflow

on:
  workflow_call:
    inputs:
      dry:
        required: true
        type: string

env:
  DRY: ${{ inputs.dry }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Go
        uses: ./.github/actions/setup-go

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: 'v0.4.2'
          install: true

      - name: Build and Push Image
        if: env.DRY == 'false'
        env:
          BUILD_ARGS: '--push'
        run: make docker-buildx

      - name: Build Image (DRY)
        if: env.DRY == 'true'
        run: make docker-buildx
