name: Reusable Workflow

on:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Go
        uses: ./.github/actions/setup-go

      - name: Build Binaries
        run: make build cli

      - name: Upload binaries to release
        if: ${{ inputs.release }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: outputs/ozctl-*
          tag: ${{ github.ref }}
          overwrite: true
