name: Release

on:
  release: {}

jobs:
  publish:
    uses: ./.github/workflows/publish.yaml
    with:
      publish: true

  helm-publish:
    needs: publish
    uses: ./.github/workflows/helm-release.yaml
