# https://github.com/marketplace/actions/validate-renovate-configuration-with-renovate-config-validator
name: renovate-config-validator
on:
  pull_request:
    paths:
      - renovate.json
      - renovate.json5
      - .github/workflows/renovate.yml

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.1.0
