name: Unit Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Run Tests
        run: make test

      - name: Report coverage
        run: make cover

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
