name: Test (End to End)

on:
  workflow_call: {}

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        kindVersion:
          - v1.26.3
          - v1.25.3
          - v1.24.7
          - v1.23.13
          - v1.22.13
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Set up Go
        uses: ./.github/actions/setup-go

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          node_image: kindest/node:${{ matrix.kindVersion }}
          kubectl_version: v1.26.3

      - name: Run E2E Tests
        run: make test-e2e
        env:
          KIND_CLUSTER_NAME: chart-testing
