name: CI

on:
  workflow_call: {}

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch History
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: ./.github/actions/setup-go

      - name: Run Tests
        env:
          KUBEBUILDER_ATTACH_CONTROL_PLANE_OUTPUT: true
        run: make test

      - name: Report coverage
        run: make cover

      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1
        with:
          infile: cover.out

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.1.1
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
